### ISSUE TITLE
ClientRequest interface

### ISSUE THREAD

**Issue by toppggg** [SeaGruppen/SEA#25]
- [x]  IClientRequests
    * ValidateSuperUser()
    * GetSurvey(SurveyId)
    * ModifySurvey(SurveyId) # Possibly (SuperUserId, SurveyId)?
    * StoreSurveyInDatabase(IModifySurvey)
    * StoreResultFromQuestion(surveyID, questionsID, UserID, Result)
    * ExportSurveyFromDatabase(Surveyid) 
    * ImportSurvey(FilePath)
    * ExportResults(SurveyId)

PR: #33

**Comment by jonasreholt** [comment]
Is it possible that `ValidateSuperUser(.)` could return a list of surveys associated to that super user (if it validates succesfully)?
If I understands it correctly we can have multiple super users with each their own set of surveys, so we need a way to get the list of associated surveys to the front end

**Comment by JacobAgertoft** [comment]
@jonasreholt  Yes I'll look into that
